import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* Each page places its own logo: the carousel wants it pinned over a
          full-viewport canvas, the admin pages want it in normal flow above
          scrolling content. A fixed one here would follow the admin page's
          scroll and sit on top of its header. */}
      <body className="min-h-full">{children}</body>
    </html>
  );
}
